# Generated by Django 3.2.9 on 2021-11-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgBot', '0006_alter_profile_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.TextField(null=True, verbose_name='Имя пользователя'),
        ),
    ]
