# Generated by Django 3.2.7 on 2021-11-18 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgBot', '0007_alter_profile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='text',
        ),
    ]
