# Generated by Django 3.2.9 on 2021-11-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgBot', '0008_remove_message_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='text',
            field=models.TextField(default='', verbose_name='Текст'),
            preserve_default=False,
        ),
    ]
